feat: Add edit api token
stargately/launch-room pull request #86
Opened 2021-04-13 20:54 UTC by killbond007

## Description

Add edit api token

<img width="1048" alt="Capture d’écran 2021-04-13 à 22 45 07" src="https://user-images.githubusercontent.com/22051991/114619730-26d89180-9cab-11eb-8a07-ffe2ac32b8dc.png">

2021-04-14 03:43 UTC, bitQ2019 commented on src/shared/api-tokens/api-tokens-resolver.ts
> +  launchRoomToken?: string;
why token can be null?

2021-04-14 03:48 UTC, bitQ2019 requested changes
The UI confuses me.
Maybe we can use a label to display the token and an editing button to update token

2021-04-14 19:03 UTC, killbond007 commented on src/shared/api-tokens/api-tokens-resolver.ts
> +  launchRoomToken?: string;
ok , i remove nullable

2021-04-15 14:09 UTC, bitQ2019 approved these changes

2021-04-15 14:10 UTC, bitQ2019 commented
> The UI confuses me.
> Maybe we can use a label to display the token and an editing button to update token

how about this?

2021-04-19 05:52 UTC, puncsky approved these changes

2021-04-19 05:52 UTC, puncsky approved these changes

2021-04-19 05:52 UTC, merged